export const recipesData = [
  {
    id: "1",
    title: "Low-Carb Avocado Chicken Salad ",
    // img: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/45b4efeb5d2c4d29970344ae165615ab/FixedFBFinal.jpg ",
    img: "./Images/ganna/Av-chicken-Salad.jpg",
    description:
      "This chicken salad is a lunchtime delight! Packed with creamy avocado, tender chicken, and crunchy veggies, it's a healthy and satisfying meal that won't weigh you down. Tossed in a tangy yogurt dressing with a hint of spice, it's a flavor explosion that's perfect for a light meal.",
    ingredients: [
      "⅔ cup plain Greek yogurt",
      "1 tablespoon lime juice",
      "Pepper, to taste",
      "⅛ teaspoon chili powder",
      "2 chicken breasts, cooked and shredded",
      "1 celery stalk, diced",
      "2 tablespoons diced red onion",
      "Kosher salt, to taste",
      "Low-carb bread, for serving, optional",
      "Fresh cilantro leaves, for garnish",
    ],
    process: [
      "In a blender or food processor, combine the yogurt, lime juice, pepper, and chili powder and pulse to combine. Add ½ of the avocado and blend until creamy.",
      "In a medium bowl, combine the chicken, yogurt sauce, celery, the remaining ½ avocado, onion, and salt. Mix until well combined.",
      "Serve on low-carb bread and garnish with cilantro, or as desired.",
      "Enjoy!",
    ],
  },
  {
    id: "2",
    title: "Tangy & Saucy Spaghetti Recipes",
    // img: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/252931.jpg ",
    img: "./Images/ganna/Tangy-spaghetti.jpg",
    description:
      "Savor the bold flavors of this Tomato and Anchovy Pasta, a perfect weeknight meal that's both simple and satisfying. With a zesty tomato sauce and umami-packed anchovies, this dish will have your taste buds dancing in no time!",
    ingredients: [
      "1 tablespoon unsalted butter",
      "10 anchovy filets, finely chopped, divided",
      "½ cup panko bread crumbs",
      "½ cup grated Parmigiano-Reggiano cheese",
      "¼ cup plus 1 tablespoon extra-virgin olive oil, divided",
      "6 cloves garlic, minced",
      "½ teaspoon red pepper flakes",
      "2 pints cherry tomatoes, halved",
      "1 teaspoon kosher salt, plus more to taste",
      "1 teaspoon kosher salt, plus more to taste",
      "1 cup white wine",
      "1 pound spaghetti, cooked al dente, ¼ cup cooking water reserved",
      "Lemon zest, to taste",
    ],
    process: [
      "Melt the butter in a large skillet over medium heat. Add 4 of the chopped anchovy filets and cook for 1 minute, until they begin to melt.",
      "Add the panko bread crumbs and cook for 3 minutes, stirring frequently, until golden brown. Transfer the bread crumbs to a medium bowl and let cool to room temperature. Once cooled, toss with the Parmigiano-Reggiano cheese.",
      "Heat ¼ cup (60 ml) of olive oil in a medium saucepan over medium-high heat. Once the oil begins to shimmer, add the remaining 6 anchovies and cook for 2 minutes, stirring frequently, until the anchovies begin to melt into the oil.",
      "Add the garlic and red pepper flakes and cook for 30 seconds, until fragrant.",
      "Add the tomatoes and stir to coat in the oil. Season with 1 teaspoon of salt and cook for 5 minutes, or until the tomatoes just begin to soften.",
      "Add the white wine and reduce the heat to low. Cook for 5 minutes, or until the sauce is reduced by half.",
      "Add cooked pasta and reserved cooking water to the pot with the tomatoes and stir to combine. Cook for 1 minute, until the pasta is well coated and saucy. Drizzle with the remaining tablespoon of olive oil and season with salt. Toss to coat.",

      "Serve the pasta topped with the anchovy bread crumbs and lemon zest",
      "Enjoy!",
    ],
  },
  {
    id: "3",
    title: "One-Pot Lemon Garlic Shrimp Pasta",
    // img: "https://img.buzzfeed.com/video-api-prod/assets/9ee2dadcbfcb4095872e6cdbaa24ff14/Thumb_A_FB.jpg ",
    img: "./Images/ganna/garlic-shrimp-pasta.jpg",
    description:
      "This easy 30-minute pasta recipe transforms ingredients that you already have in your kitchen into a posh, seafood dish you’ll want to serve at your next dinner party. And since the whole dish is made in a single pot, clean-up is easy. Don’t be surprised if this becomes your favorite quick go-to. ",
    ingredients: [
      "8 oz linguine",
      "2 Tbsp. olive oil",
      "8 Tbsp. (1 stick) unsalted butter",
      "1 stick",
      "4 cloves garlic, minced",

      "1 tsp crushed red pepper",
      "1¼ lbs large shrimp",
      "Salt and pepper to taste",

      "1 tsp dried oregano",
      "4 cups baby spinach",
      "¼ cup Parmesan",
      "2 Tbsp. parsley, chopped",
      "1 Tbsp. lemon juice",
    ],
    process: [
      "In a large pot, boil water and add pasta. Cook (stirring frequently) until al dente.",
      "Drain and set pasta aside.",
      "In the same pan, heat olive oil and 2 tablespoons of butter. Add garlic and crushed red pepper, cook until fragrant.",
      "Toss in shrimp, salt and pepper to taste, and stir until shrimp start to turn pink, but are not fully cooked.",
      "Add oregano and spinach, cook until wilted.",
      "Return cooked pasta to the pot, add remaining butter, parmesan, and parsley. Stir until well mixed and the butter is melted.",
      "When the shrimp are cooked, add lemon juice, mix once more, then serve while hot.",
      "Enjoy!",
    ],
  },
];
